export default {
    plugins: {
        'postcss-import': {},
        'tailwindcss/nesting': {},
        tailwindcss: {},
        'postcss-pxtorem': {
            propList: [
                'font',
                'font-size',
                'line-height',
                'letter-spacing',
                'padding',
                'margin',
                'padding-*',
                'margin-*',
                'width',
                'height',
                'min-width',
                'min-height',
                'max-width',
                'max-height',
                'left',
                'right',
                'top',
                'bottom',
                'border-radius',
                'background-position',
                'background-size',
                'transform',
                'column-gap',
                'row-gap',
                'gap',
            ],
        },
        autoprefixer: {},
    },
};
